### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by evehal** [tksuoran/erhe#120]
CMake Error: The inter-target dependency graph contains the following strongly connected component (cycle):
  "erhe_log" of type SHARED_LIBRARY
    depends on "erhe_time" (weak)
  "erhe_time" of type SHARED_LIBRARY
    depends on "erhe_log" (weak)
At least one of these targets is not a STATIC_LIBRARY.  Cyclic dependencies are allowed only among static libraries.
CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by tksuoran** [comment]
How are you doing cmake configure, what is your build environment?
So far I have only built erhe using static libraries. I'll see if I can repro and see how to fix this.
I suppose some or all erhe libraries could be explicitly added as static libraries.

**Comment by tksuoran** [comment]
You could set BUILD_SHARED_LIBS off, for example by passing `-DBUILD_SHARED_LIBS=ON` to cmake.

**Comment by evehal** [comment]
thank you tksuoran,it works by setting build shared libs off
