### ISSUE TITLE
Cloning into 'freetype-src'... - error

### ISSUE THREAD

**Issue by Phobos03** [tksuoran/erhe#33]
Cloning into 'freetype-src'... - problem, for the reference I include screenshot
![DeepinScreenshot_select-area_20220612155157](https://user-images.githubusercontent.com/17527075/173236820-202dcc4c-cf0a-42da-9177-104f9d0f4090.png)
.

**Comment by Phobos03** [comment]
Bug was fixed.

**Comment by tksuoran** [comment]
This was an issue due to freedesktop gitlab being down. I think it is back niw, but I also changed cmake fetchcontent to use mirror in github.
