### ISSUE TITLE
issue with mango

### ISSUE THREAD

**Issue by Phobos03** [tksuoran/erhe#40]
I'm sorry I didn't say a word. I try to compile the newest main branch but I have issue. 

In file included from /home/daniel/CLionProjects/erhe/src/erhe/application/rendergraph/rendergraph_node.cpp:6:
/home/daniel/CLionProjects/erhe/src/mango/include/mango/math/vector256_int8x32.hpp:7:10: fatal error: mango/math/vector.hpp: No such file or directory
    7 | #include <mango/math/vector.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/erhe/application/CMakeFiles/erhe_application.dir/build.make:356: src/erhe/application/CMakeFiles/erhe_application.dir/rendergraph/rendergraph_node.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1611: src/erhe/application/CMakeFiles/erhe_application.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

**Comment by tksuoran** [comment]
Fixed now I hope

**Comment by Phobos03** [comment]
Yes, It's working now.

**Comment by tksuoran** [comment]
By the way, which toolchain you use? I tried the default mingw toolchain
and it is very, very slow in linking. Everything else builds erhe in about
two minutes on the computer I use, but mingw that is bundled with clion
took 28 minutes..

Best regards,
Timo
