### ISSUE TITLE
[Feature Request] Options window to adjust certain aspects of the engine

### ISSUE THREAD

**Issue by deccer** [tksuoran/erhe#57]
Hi Timo, I finally bend down to open an issue :)

Since im suffering on low performance hardware I was thinking if its possible for you to add a window of sorts where various aspects of the engine can be adjusted using buttons and knobs etc, so that I don't (or you even :D) have to edit `erhe.ini` manually anymore

I was thinking about something like adjusting window state (whether app opens in fullscreen/fullscreen window/window), msaa, shadow map size, amount of lights and each being able to cast shadows, shadow quality (im sure in the shaders are some sort of variable settings too regarding sampling), how smooth certain things are, and probably all the rest of erhe.ini values too 

Possibly in a way that i can select from a low/mid/high quality preset as well. You decide on what options are sensible for low/mid/high settings (or we try and see in #erhe to find out)

PS erhe is my favourite Pots & Pans Kitchen Simulator :froge-heart:

**Comment by tksuoran** [comment]
There is initial minimal graphics presets thing now.

**Comment by tksuoran** [comment]
Dependencies:
- [ ] #112

**Comment by tksuoran** [comment]
More stuff is now serialized/persistent.
